env:
  - DATABASE_URL="postgres://postgres@localhost/deep_thought_test"

language: ruby

install: bundle install --binstubs

before_script: psql -c 'create database deep_thought_test;' -U postgres; bundle exec rake db:migrate RACK_ENV=test
script: script/test
